### Data Types in NumPy Arrays

**1. Installing NumPy**

In [1]:
!pip install numpy

**2. Importing NumPy**

In [2]:
import numpy as np

**3. Checking the NumPy Version**

In [3]:
np.__version__

'2.5.2'

**4. NumPy 1D, 2D, and 3D Arrays**

In [4]:
# 1D array
# A 1D array is like a single row of values.
# Here, the array contains four elements.
a1d = np.array([1, 2, 3, 4])
a1d

array([1, 2, 3, 4])

In [5]:
print(type(a1d))

<class 'numpy.ndarray'>


In [6]:
# shape
# shape tells us the size of the array along each dimension.
# (4,) means 4 elements along one dimension.
a1d.shape

(4,)

In [7]:
# size
# size gives the total number of elements in the array.
a1d.size

4

In [8]:
# length
# len() gives the length of the first dimension.
# For a 1D array, this is the same as the number of elements.
len(a1d)

4

In [9]:
# A 2D array can be created using nested lists.
# Further nesting creates higher-dimensional arrays.
# In NumPy, an array object is generally called an ndarray.
# Nested lists create a 2D array: rows × columns.
# This array has 2 rows and 3 columns.
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# (2, 3) means 2 rows and 3 columns.
arr.shape

(2, 3)

In [11]:
# 3D array
# A 3D array can be visualized as multiple 2D matrices stacked together.
# Here we have 2 blocks, each containing 2 rows and 2 columns.
a3d_list = [
    [
        [1,2],[3,4]
    ], [
        [5,6],[7,8]
    ]
]

In [12]:
arr = np.array(a3d_list)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
# (2, 3) means 2 rows and 3 columns.
arr.shape

(2, 2, 2)

In [14]:
arr.size

8

**5. Supported Data Types in NumPy**
- NumPy arrays (ndarrays) are homogeneous, meaning their elements normally share the same data type.

*1. Integer Data Type*

In [15]:
np.array([1, 2, 3])

array([1, 2, 3])

In [16]:
# dtype lets us explicitly control how the values are stored.
# int32 uses 32 bits (4 bytes) per integer.
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

*2. Float Data Type*

In [17]:
np.array([1.2, 2.2, 3.2])

array([1.2, 2.2, 3.2])

In [18]:
# float32 stores decimal values using 32 bits per value.
np.array([1.2, 2.2, 3.2], dtype=np.float32)

array([1.2, 2.2, 3.2], dtype=float32)

In [19]:
# Converting floats to integers removes the decimal part.
# For example, 1.2 becomes 1.
np.array([1.2, 2.2, 3.2], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [20]:
# When different numeric types are mixed, NumPy promotes them
# to a common type that can represent all values.
np.array([1, 2.7]) # NumPy automatically upcasts them to the most compatible common type.

array([1. , 2.7])

*3. Boolean Data Type*

In [21]:
np.array([True, False, True], dtype=bool)

array([ True, False,  True])

In [22]:
# Boolean values are converted to integers: True → 1 and False → 0.
np.array([True, False, True], dtype=np.int32)

array([1, 0, 1], dtype=int32)

*4. String Data Type*

In [23]:
# NumPy stores these strings using a Unicode string dtype.
np.array(["apple", "Banana"])

array(['apple', 'Banana'], dtype='<U6')

In [24]:
# U10 means a Unicode string with a maximum length of 10 characters.
np.array(["apple", "Banana"], dtype='U10')  # Unicode strings, each up to 10 characters long

array(['apple', 'Banana'], dtype='<U10')

In [25]:
# U3 limits each string to 3 characters, so longer strings are truncated.
np.array(["apple", "Banana"], dtype='U3')  # U3 means each string can contain up to 3 characters

array(['app', 'Ban'], dtype='<U3')

In [26]:
# Mixing data types
# Mixing integers and strings causes NumPy to choose a common compatible dtype.
# Here, the integers are converted to strings.
np.array([1,'2',3])   

array(['1', '2', '3'], dtype='<U21')

In [27]:
# This works because the string '2' can be converted to an integer.
np.array([1,'2',3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [28]:
# This raises an error because 'b' cannot be converted to an integer.
np.array([1,'b',3], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'b'

**6. Record Arrays or Structured Arrays**
- Structured arrays in NumPy are homogeneous at the array level, meaning each element follows the same structure.
- You can define a data type and an optional name for each field (column). This makes the data easier to access, sort, and filter, similar to working with Excel, CSV files, or relational databases.

In [ ]:
# Each tuple represents one record: (name, age, marks).
# A Python list of tuples can later be converted into a structured NumPy array.
records = [
    ("aman", 22,90),
    ("ankit",15, 68),
    ("akash",18, 90),
    ("aditya",22, 80)
]

In [ ]:
records

[('aman', 22, 90), ('ankit', 15, 68), ('akash', 18, 90), ('aditya', 22, 80)]

In [ ]:
# Without a structured dtype, NumPy finds one common dtype for the entire array.
# Because names are strings, the numeric values are also converted to strings.
data = np.array(records)
data

array([['aman', '22', '90'],
       ['ankit', '15', '68'],
       ['akash', '18', '90'],
       ['aditya', '22', '80']], dtype='<U21')

In [ ]:
# A structured dtype lets each field have its own data type and name.
# This keeps name as a string and age/marks as integers.
data = np.array(records, dtype = [("name", "U15"), ("age", np.int32),("marks",np.int32)])
data

array([('aman', 22, 90), ('ankit', 15, 68), ('akash', 18, 90),
       ('aditya', 22, 80)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

**You can specify `dtype` (data type) in several equivalent ways:**

- Using NumPy type strings (compact format): `[("name", "U15"), ("age", "i4"), ("marks", "i4")]`
- Using NumPy type objects: `[("name", np.unicode_), ("age", np.int32), ("marks", np.int32)]`
- Mixing Python built-in types and NumPy types: `[("name", str), ("age", int), ("marks", np.int32)]`

In [ ]:
# Access the first complete record.
data[0]

np.void(('aman', 22, 90), dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

In [ ]:
# Access the first complete record.
print(data[0])

('aman', 22, 90)


In [ ]:
# Field names let us select one column directly.
data["name"]

array(['aman', 'ankit', 'akash', 'aditya'], dtype='<U15')

**By default, NumPy arrays (ndarrays) are homogeneous, meaning their elements share the same data type. This provides several advantages:**

- 1. Vectorized operations
- 2. Efficient memory layout (contiguous blocks)
- 3. Fast computations using C under the hood

* **NumPy** is designed to work efficiently with fixed-size elements, especially numerical data such as integers and floats. It also supports strings, booleans, dates, and custom structured data types.

* All elements in a standard NumPy array share the same data type (`dtype`).

* The data is stored in a contiguous block of memory, which improves memory efficiency and computational speed.

NumPy can also represent heterogeneous data using object arrays or structured dtypes, but object arrays generally lose many of NumPy's performance advantages.

In [ ]:
# An object array can store different Python object types in the same array.
# This provides flexibility, but usually sacrifices NumPy's performance advantages.
het = np.array([5,4.5, True, "6.5","C"])
het

array(['5', '4.5', 'True', '6.5', 'C'], dtype='<U32')

In [ ]:
# dtype='U32' means the values are stored as Unicode strings.
# NumPy converted the mixed values to a common string representation.
het.dtype  # The mixed values are converted to a common compatible type

dtype('<U32')

In [ ]:
het[0]

np.str_('5')

In [ ]:
# NumPy treats this as an array of generic Python objects.
# Object arrays generally lose the performance benefits of NumPy's vectorized operations.
# Operations such as addition and broadcasting may therefore be less efficient.
# An object array can store different Python object types in the same array.
# This provides flexibility, but usually sacrifices NumPy's performance advantages.
het = np.array([5,4.5, True, "6.5","C"], dtype=object)
het

array([5, 4.5, True, '6.5', 'C'], dtype=object)

In [ ]:
het.dtype

dtype('O')

In [ ]:
# With dtype=object, the original Python object type is preserved.
print(type(het[0]))

<class 'int'>


In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or i