### Create Numpy Arrays

In [345]:
import numpy as np

**From built-in python conatiner(Lists, tuple etc)**

In [346]:
# using List
# Convert a Python list into a NumPy array
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [347]:
# using tuple
# Convert a Python tuple into a NumPy array
np.array((1,2,3,4))

array([1, 2, 3, 4])

**Upcasting in Numpy**

* Upcasting in NumPy refers to the automatic conversion of data types when performing operations involving arrays of different types, so that no data is lost and the result has a compatible type that can hold all input values.

In [348]:
# NumPy promotes the integers to float to use a common dtype
np.array([1,2.5,3,4])

array([1. , 2.5, 3. , 4. ])

**Two Dimensional numpy array**

In [349]:
np.array([
    [1,2,3],
    [4,5,6
    ]
])

array([[1, 2, 3],
       [4, 5, 6]])

**minimum dimensions 2**

In [350]:
# ndmin=2 ensures that the array has at least 2 dimensions
np.array([1,2,3,4], ndmin=2)

array([[1, 2, 3, 4]])

**dtype**

In [351]:
# dtype=complex creates an array of complex numbers
np.array([1,2,3,4], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

**data consisting of more than one data-type**

In [352]:
x = np.array([(1,2),(3,4.2)], dtype=[('a','i4'),('b',np.float32)])
x

array([(1, 2. ), (3, 4.2)], dtype=[('a', '<i4'), ('b', '<f4')])

In [353]:
x['a']

array([1, 3], dtype=int32)

In [354]:
x['b']

array([2. , 4.2], dtype=float32)

**np.asarray**
- np.array() => Always creates a new array (i.e., it copies data). Even if the input is already a NumPy array
- np.asarray() => Just ensure object is a NumPy array

In [355]:
a = [1,2]
# Convert the input to a NumPy array without an unnecessary copy
np.asarray(a)

array([1, 2])

In [356]:
a = np.array([1,2]) # Existing arrays are not copied
a

array([1, 2])

In [357]:
# Convert the input to a NumPy array without an unnecessary copy
np.asarray(a) is a

True

In [358]:
# False means a separate array object was created
np.array(a) is a

False

*If dtype is set, array is copied only if dtype does not match:*

In [359]:
a = np.array([1,2], dtype=np.float32)

In [360]:
# A different dtype requires a new array
np.asarray(a, dtype=np.float64) is a # it create new array becoase data type is diffrenetr

False

**numpy.copy**

In [361]:
a

array([1., 2.], dtype=float32)

In [362]:
# copy=True creates an independent array
np.array(a, copy=True) is a

False

In [363]:
# copy=False avoids copying when possible
np.array(a, copy=False) is a

True

**create an array x, with a reference y and a copy z**

In [364]:
# Create the original array
x = np.array([1,2,3])

In [365]:
y = x # refrences

In [366]:
# z is an independent copy of x
z = np.copy(x) # copy

**when we modify x,y changes, but not z**

In [367]:
# Changing x also changes y, but not z
x[0] = 10

In [368]:
x

array([10,  2,  3])

In [369]:
y

array([10,  2,  3])

In [370]:
z

array([1, 2, 3])

**Read and write data from a file**

*1. Text file(.txt, .csv)*

In [371]:
# Read numerical data from a comma-separated text file
data = np.loadtxt('data/data.txt', delimiter=',')
data

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [372]:
data = data ** 2
data

array([[ 1.,  4.,  9.],
       [16., 25., 36.],
       [49., 64., 81.]])

In [373]:
# Save the array to a text file
np.savetxt("data/output_data.txt", data, fmt="%f")

*2. Binary file(.npy,.npz)*

In [374]:
# Convert a Python list into a NumPy array
arr = np.array([1,2,3,4])
np.save("data/array.npy",arr)

In [375]:
# Load the saved NumPy array
arr = np.load("data/array.npy")
print(arr)

[1 2 3 4]


In [376]:
# save multiple arrays
a =np.array([1,2,3])
b = np.array([4,5,6])
# Save multiple arrays in one .npz file
np.savez('data/arrays.npz', arr1=a, arr2=b)


In [377]:
# load them back
# Load the .npz file containing multiple arrays
data = np.load("data/arrays.npz")
print(data)

NpzFile 'data/arrays.npz' with keys: arr1, arr2


In [378]:
print(data["arr1"])
print(data["arr2"])

[1 2 3]
[4 5 6]


| File Format | Read Function | Write Function | Notes |
|---|---|---|---|
| `.txt` / `.csv` | `loadtxt()` / `genfromtxt()` | `savetxt()` | Use `delimiter` for custom separators |
| `.npy` | `load()` | `save()` | For a single NumPy array (binary format) |
| `.npz` | `load()` | `savez()` / `savez_compressed()` | For storing multiple arrays |

**Advantages of `.npy` and `.npz` over Text Files**

| Feature | `.npy` / `.npz` (Binary) | `.txt` / `.csv` (Text) |
|---|---|---|
| Efficiency | Much faster to read/write | Slower I/O |
| Storage Size | More compact | Larger file size |
| Multiple Arrays | `.npz` can store multiple arrays in one file | Not directly supported; usually requires multiple files |
| No Parsing Needed | Directly loads as a NumPy array | Requires delimiter and dtype parsing |
| Reliability | Less sensitive to formatting issues | Can be affected by extra spaces, missing values, or formatting inconsistencies |


**numpy.fromfunction**

In [379]:
# Create values using row and column indices
np.fromfunction(lambda i,j : i ==j ,(3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [380]:
# Calculate each value from its row and column indices
np.fromfunction(lambda i,j : i +j ,(3,3), dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [381]:
# A new 1D array initializes from text data in a string
# Convert numbers stored in a string into a NumPy array
np.fromstring('1 2', dtype=int, sep=' ')

array([1, 2])

**Create a record array from a (flat) list of arrays**

In [382]:
x1 = [1,2,3]
x2 = [4.0,5.0,6.0]
x3 = ["a",'b','c']

In [383]:
a = list(zip(x1, x2, x3))

In [384]:
r = np.array(a , dtype=[('a','i4'),('b','f4'),('c',"U1")])
r

array([(1, 4., 'a'), (2, 5., 'b'), (3, 6., 'c')],
      dtype=[('a', '<i4'), ('b', '<f4'), ('c', '<U1')])

In [385]:
r["a"]

array([1, 2, 3], dtype=int32)

**data types**

In [386]:
my_list = [1,2,3]
arr = np.array(my_list)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


In [387]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print(type(mat))
print(mat,"\n-----------")
print("dimension of the matrix: ", mat.ndim, sep='')

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
dimension of the matrix: 2


In [388]:
#size gives the total number of elements
print("Size of this matrix: ", mat.size,sep='')

#shape gives the number of elements along each axes (dimension)
print("Shape of this matrix: ", mat.shape,sep='') 

#dtype gives the data type contained in the array
print("Data type of this matrix: ", mat.dtype,sep='') 

Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [389]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)

print("Data type of the modified matrix: ", mat.dtype,sep='') 
#dtype gives the data type contained in the array

Data type of the modified matrix: float64


In [390]:
b = np.array([(1.5,2,3), (4,5,6)])

print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]
