### Intoducation to Numpy

In [1]:
import numpy as np

In [4]:
# checking numpy version
np.__version__

'2.5.1'

#### Numpy 1D, 2D and 3D array

In [5]:
# 1 d array
a1d = np.array([1,2,3,4])
a1d

array([1, 2, 3, 4])

In [7]:
print(type(a1d))

<class 'numpy.ndarray'>


In [8]:
help(np.array)

Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if 

In [9]:
# shape
a1d.shape

(4,)

In [10]:
# size 
a1d.size

4

In [11]:
# len 
len(a1d)

4

In [12]:
# 2d Array => list of list
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr.shape

(2, 3)

In [14]:
# 3d array
a3d = np.array([
    [   [1,2], [3,4]
     
     ], [
         [5,6],[7,8]
     ]
])

In [15]:
a3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
a3d.shape

(2, 2, 2)

In [18]:
a3d.size

8

#### supported datatypes in numpy
- numpy arrays (ndarrays) are homogeneous, meaning all element must be of the same data type.

In [19]:
np.array([1,2,3])

array([1, 2, 3])

In [20]:
np.array([1,2,3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [22]:
np.array([1.2,2.2,3.3], dtype=np.float32)

array([1.2, 2.2, 3.3], dtype=float32)

In [23]:
np.array([1.2,2.2,3.3], dtype=np.int32) # we loose some data

array([1, 2, 3], dtype=int32)

In [26]:
np.array([True, False, True], dtype=np.int32)

array([1, 0, 1], dtype=int32)

In [28]:
np.array(['apple','banana'],dtype='U10')

array(['apple', 'banana'], dtype='<U10')

In [31]:
np.array(['apple','banana'],dtype='U5')  # maxium len of each element 5

array(['apple', 'banan'], dtype='<U5')

In [32]:
np.array([1,'2',3])

array(['1', '2', '3'], dtype='<U21')

In [33]:
np.array([1,'2',3], dtype=np.int32)

array([1, 2, 3], dtype=int32)

In [34]:
np.array([1,'b',3], dtype=np.int32)

ValueError: invalid literal for int() with base 10: 'b'

#### record array or structured array

- structured array in numpy are homogeneous at the array level (each element has the same layout)
- we can specify a type and optionally, a name on a per-column basic. This makes sorting and filtering even more powerful, and it can feel similar to working withd ata in Excell CSv's or relational databases.

In [35]:
records = [
    ("aman", 22,90),
    ('ankit', 15,60),
    ('akash', 18,90),
    ('aditya',22,80)
]

In [36]:
records

[('aman', 22, 90), ('ankit', 15, 60), ('akash', 18, 90), ('aditya', 22, 80)]

In [37]:
data = np.array(records)
data

array([['aman', '22', '90'],
       ['ankit', '15', '60'],
       ['akash', '18', '90'],
       ['aditya', '22', '80']], dtype='<U21')

In [38]:
data = np.array(records, dtype=[("name","U15"),("age",np.int32),("marks",np.int32)])
data

array([('aman', 22, 90), ('ankit', 15, 60), ('akash', 18, 90),
       ('aditya', 22, 80)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

You can specify the `dtype` (data type) in several equivalent ways.

1. **Using NumPy type strings (compact format):** `[("name", "U15"), ("age", "i4"), ("marks", "i8")]`
2. **Using NumPy type objects (recommended):** `[("name", np.unicode_), ("age", np.int8), ("marks", np.int32)]`
3. **Mixing Python built-in types and NumPy types:** `[("name", str), ("age", int), ("marks", np.int32)]`

In [39]:
data[0]

np.void(('aman', 22, 90), dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<i4')])

In [40]:
print(data[0])

('aman', 22, 90)


In [41]:
data["name"]

array(['aman', 'ankit', 'akash', 'aditya'], dtype='<U15')

#### NumPy Arrays Are Homogeneous

By default, NumPy arrays (`ndarray`) are **homogeneous**, meaning all elements must be of the same data type.

#### Homogeneous arrays allow:

1. **Vectorized operations**
2. **Efficient memory layout** (contiguous blocks)
3. **Fast computations using C under the hood**

- NumPy is designed for arrays of fixed-size elements — typically numerical data types (integers, floats), but also supports strings, booleans, dates, and custom types.
- All elements in a NumPy array share the same data type (`dtype`).
- The data is stored in a **contiguous block of memory** for efficiency.

> It can support heterogeneous types using object arrays or structured dtypes, but these lose most performance benefits.

In [42]:
het = np.array([5,4.5,True, 6.5, 'c'])
het

array(['5', '4.5', 'True', '6.5', 'c'], dtype='<U32')

In [43]:
het.dtype

dtype('<U32')

In [44]:
het[0]

np.str_('5')

In [45]:
het = np.array([5,4.5,True, 6.5, 'c'], dtype='object')
het

array([5, 4.5, True, 6.5, 'c'], dtype=object)

In [46]:
het.dtype

dtype('O')

In [48]:
print(type(het[0]))

<class 'int'>
