#### Numpy 

In [43]:
import numpy as np

**Creating arrays**

In [44]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [45]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [47]:
# convert list into numpy array
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [48]:
# Access the element in the array
a[2]

np.int64(3)

In [49]:
# modify the element
a[2] =10
a

array([ 1,  2, 10,  5,  7, 12])

In [50]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [52]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

**Mulit-dimentional arrays**

In [53]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [54]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [55]:
# Access the element
print(n[0])
print(n[0,0])
print(n[0:2])
print(n[0:2,2])

[1 2 3]
1
[[1 2 3]
 [4 5 6]]
[3 6]


In [56]:
# modify 
n[0,1] = 10
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [57]:
# modify the rows
n[2] = [1,1,1]
n

array([[ 1, 10,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [58]:
n[:,1]

array([10,  5,  1])

In [59]:
n[:,2] = [0, 1, 2]
n

array([[ 1, 10,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

**Randomly generated arrays**

In [70]:
np.random.seed(5)
100 * np.random.rand(5,2)

array([[22.19931711, 87.07323062],
       [20.67191553, 91.86109079],
       [48.84111888, 61.17438629],
       [76.59078565, 51.84179879],
       [29.68005016, 18.77212287]])

In [68]:
np.random.seed(5)
np.random.randn(5,2)

array([[ 0.44122749, -0.33087015],
       [ 2.43077119, -0.25209213],
       [ 0.10960984,  1.58248112],
       [-0.9092324 , -0.59163666],
       [ 0.18760323, -0.32986996]])

In [72]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

**Elemement-wise operations**

In [73]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [74]:
a + 1

array([1, 2, 3, 4, 5])

In [75]:
a * 2

array([0, 2, 4, 6, 8])

In [76]:
a / 100

array([0.  , 0.01, 0.02, 0.03, 0.04])

In [81]:
b = (10 + (a *2)) **2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [82]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

**Comparison operations**

In [83]:
a

array([0, 1, 2, 3, 4])

In [84]:
a >=2

array([False, False,  True,  True,  True])

In [85]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [86]:
a > b

array([False, False,  True,  True,  True])

In [87]:
a[a>b]

array([2, 3, 4])

**Summarizing operations**

In [88]:
a.min()

np.int64(0)

In [89]:
a.max()

np.int64(4)

In [90]:
a.sum()

np.int64(10)

In [91]:
a.mean()

np.float64(2.0)

In [92]:
a.std()

np.float64(1.4142135623730951)

In [93]:
n

array([[ 1, 10,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [94]:
n.sum()

np.int64(25)